### ISSUE TITLE
Render for Hugo pages

### ISSUE THREAD

**Issue by Whyeasy** [SierraSoftworks/roadmap#273]
Hi,

It would be great if it was possible to render markdown pages for [Hugo](https://gohugo.io/). Now we need to copy paste the mandatory headers back into the markdown that we generated.

In this case there needs to be a few extra additions to the outputted markdown.

```markdown
---
title: <- minimum - Could be fetched from title in yaml
description: <- nice to have - Could be fetched from description in yaml
weight: <- nice to have - This determines the order of items in the menu
---
```

**Comment by notheotherben** [comment]
Hi, this sounds like a great idea - I've created #274 to add this functionality, and please shout if you run into any issues with its use (for fields like `weight` I've included a `--frontmatter '<valid yaml>'` flag which can be used to specify any series of properties you'd like to add, which should give you a fair bit of flexibility here.
